var toExport = {}
var d2, d3, doo, lines, text, ts

import Do from "../editor/Do.js"

toExport["Do"] = function ()
{
    section("setLines", function ()
    {
        text = "hello\nworld"
        lines = text.split('\n')
        doo = new Do
        doo.setLines(lines)
        compare(doo.lines(),lines)
        compare(doo.text(),text)
    })
    section("insert", function ()
    {
        doo.insert(1,'beautiful')
        compare(doo.lines(),['hello','beautiful','world'])
        doo.insert(3,'!')
        compare(doo.lines(),['hello','beautiful','world','!'])
        doo.insert(666,'?')
        compare(doo.lines(),['hello','beautiful','world','!'])
        doo.insert(-666,'▴')
        compare(doo.lines(),['hello','beautiful','world','!'])
    })
    section("delete", function ()
    {
        doo = new Do(lines)
        doo.delete(0)
        compare(doo.lines(),['world'])
        doo.delete(1)
        compare(doo.lines(),['world'])
        doo.delete(-2)
        compare(doo.lines(),['world'])
        doo.delete(-1)
        compare(doo.lines(),[])
    })
    section("change", function ()
    {
        doo = new Do(['hello','world','○'])
        doo.change(2,'~')
        compare(doo.lines(),['hello','world','~'])
        doo.change(-1,'!!')
        compare(doo.lines(),['hello','world','!!'])
        doo.change(-3,'hi')
        compare(doo.lines(),['hi','world','!!'])
        doo.change(-5,'blork')
        compare(doo.lines(),['hi','world','!!'])
        doo.change(666,'blark')
        compare(doo.lines(),['hi','world','!!'])
    })
    section("undo", function ()
    {
        doo = new Do(['a','b','c'])
        doo.start()
        doo.insert(1,'d')
        doo.change(2,'C')
        doo.end()
        compare(doo.lines(),['a','d','C','c'])
        doo.undo()
        compare(doo.lines(),['a','b','c'])
        doo.undo()
        compare(doo.lines(),['a','b','c'])
    })
    section("redo", function ()
    {
        compare(doo.lines(),['a','b','c'])
        doo.redo()
        compare(doo.lines(),['a','d','C','c'])
        doo.redo()
        compare(doo.lines(),['a','d','C','c'])
        doo.redo()
        compare(doo.lines(),['a','d','C','c'])
    })
    section("tabState", function ()
    {
        compare(doo.tabState(),[{'■ 1':'■d■','● 2':'●C●'}])
        doo = new Do([])
        compare(doo.tabState(),[])
        doo.start()
        doo.insert(0,'bla')
        doo.insert(0,'blub')
        doo.end()
        compare(doo.lines(),['blub','bla'])
        compare(doo.tabState(),[{'● 0':'●blub●','● 1':'●bla●'}])
        doo.start()
        doo.insert(1,'')
        doo.insert(3,'')
        doo.end()
        compare(doo.lines(),['blub','','bla',''])
        compare(doo.tabState(),[{'● 0':'●blub●','● 1':'●bla●'},{'● 1':'●●','● 3':'●●'}])
        compare(doo.history.length,3)
        doo.start()
        doo.change(1,'krep')
        doo.change(3,'krap')
        doo.end()
        compare(doo.lines(),['blub','krep','bla','krap'])
        compare(doo.tabState(),[{'● 0':'●blub●','● 1':'●bla●'},{'● 1':'●●','● 3':'●●'},{'■ 1':'■krep■','■ 3':'■krap■'}])
        doo.undo()
        compare(doo.tabState(),[{'● 0':'●blub●','● 1':'●bla●'},{'● 1':'●●','● 3':'●●'}])
        doo.redo()
        ts = doo.tabState()
        compare(ts,[{'● 0':'●blub●','● 1':'●bla●'},{'● 1':'●●','● 3':'●●'},{'■ 1':'■krep■','■ 3':'■krap■'}])
        d2 = new Do([])
        d2.setTabState(ts)
        compare(d2.lines(),['blub','krep','bla','krap'])
        compare(d2.tabState(),ts)
    })
    section("tabState delete", function ()
    {
        doo = new Do(['kermit','alfred','gonzo'])
        doo.start()
        doo.delete(1)
        doo.end()
        compare(doo.lines(),['kermit','gonzo'])
        ts = doo.tabState()
        compare(ts,[{'○ 1 1':'○'}])
        d2 = new Do(['kermit','alfred','gonzo'])
        d2.setTabState(ts)
        compare(d2.lines(),['kermit','gonzo'])
        compare(d2.tabState(),ts)
        d2.start()
        d2.delete(0)
        d2.delete(0)
        d2.end()
        compare(d2.lines(),[])
        ts = d2.tabState()
        compare(ts,[{'○ 1 1':'○'},{'○ 0 0':'○','○ 0 1':'○'}])
        d3 = new Do(['kermit','alfred','gonzo'])
        d3.setTabState(ts)
        compare(d3.lines(),[])
    })
}
toExport["Do"]._section_ = true
toExport._test_ = true
export default toExport
