# level design by Michael Abel

# .................................................................................................................
level_dict["random"] = {   
                        "scheme":   "default_scheme",
                        "size":     (21,21,21),
                        "intro":    "random",    
                        "help":     ( 
                                        "$scale(1.5)mission:\nget to the exit!\n\n" + \
                                        "jump and try",
                                    ),
                        "player":   {   "coordinates":     (1,3,2),
                                        "nostatus":         0,
                                    },
                        "exits":    [
                                        {
                                            "name":         "exit",
                                            "active":       1,
                                            "position":     (0,0,0),
                                        },
                                    ],
                        "create":
"""
#startblock
world.addObjectAtPos (KikiWall(), KikiPos(1,2,2))
world.addObjectAtPos (KikiWall(), KikiPos(1,18,2))
world.addObjectAtPos (KikiWall(), KikiPos(1,2,18))
world.addObjectAtPos (KikiWall(), KikiPos(1,18,18))

world.addObjectAtPos (KikiWall(), KikiPos(19,2,2))
world.addObjectAtPos (KikiWall(), KikiPos(19,18,2))
world.addObjectAtPos (KikiWall(), KikiPos(19,2,18))
world.addObjectAtPos (KikiWall(), KikiPos(19,18,18))

#h=[0,19]
#for (i,j,l) in [ (i,j,l) for i in h for j in h for l in h]:
#	world.addObjectAtPos (KikiLight	(), KikiPos (i,j,l))

world.addObjectAtPos (KikiLight	(), KikiPos (0,0,0))
world.addObjectAtPos (KikiLight	(), KikiPos (20,20,20))

world.addObjectAtPos (KikiStone(), KikiPos(3,2,6))
world.addObjectAtPos (KikiStone(), KikiPos(5,2,6))
world.addObjectAtPos (KikiStone(), KikiPos(12,4,6))
world.addObjectAtPos (KikiStone(), KikiPos(14,16,6))
world.addObjectAtPos (KikiStone(), KikiPos(2,16,4))
world.addObjectAtPos (KikiStone(), KikiPos(2,14,15))
world.addObjectAtPos (KikiStone(), KikiPos(2,12,13))
world.addObjectAtPos (KikiStone(), KikiPos(4,4,13))
world.addObjectAtPos (KikiStone(), KikiPos(6,4,11))
world.addObjectAtPos (KikiStone(), KikiPos(8,4,13))
world.addObjectAtPos (KikiStone(), KikiPos(8,6,11))
world.addObjectAtPos (KikiStone(), KikiPos(6,6,4))
world.addObjectAtPos (KikiStone(), KikiPos(8,5,4))
world.addObjectAtPos (KikiStone(), KikiPos(10,6,4))
world.addObjectAtPos (KikiStone(), KikiPos(8,17,4))
world.addObjectAtPos (KikiStone(), KikiPos(10,15,4))
world.addObjectAtPos (KikiStone(), KikiPos(8,15,6))
world.addObjectAtPos (KikiStone(), KikiPos(8,13,10))
world.addObjectAtPos (KikiStone(), KikiPos(6,13,12))
world.addObjectAtPos (KikiStone(), KikiPos(5,15,12))
world.addObjectAtPos (KikiStone(), KikiPos(5,15,14))
world.addObjectAtPos (KikiStone(), KikiPos(3,17,14))
world.addObjectAtPos (KikiStone(), KikiPos(15,15,14))
world.addObjectAtPos (KikiStone(), KikiPos(9,13,14))
world.addObjectAtPos (KikiStone(), KikiPos(7,13,14))
world.addObjectAtPos (KikiStone(), KikiPos(7,15,12))
world.addObjectAtPos (KikiStone(), KikiPos(7,13,7))
world.addObjectAtPos (KikiStone(), KikiPos(7,12,5))
world.addObjectAtPos (KikiStone(), KikiPos(5,12,11))
world.addObjectAtPos (KikiStone(), KikiPos(7,7,11))
world.addObjectAtPos (KikiStone(), KikiPos(5,7,13))
world.addObjectAtPos (KikiStone(), KikiPos(3,17,13))
world.addObjectAtPos (KikiStone(), KikiPos(18,17,11))
world.addObjectAtPos (KikiStone(), KikiPos(18,7,9))
world.addObjectAtPos (KikiStone(), KikiPos(15,9,9))
world.addObjectAtPos (KikiStone(), KikiPos(17,11,9))
world.addObjectAtPos (KikiStone(), KikiPos(15,11,5))
world.addObjectAtPos (KikiStone(), KikiPos(13,11,3))
world.addObjectAtPos (KikiStone(), KikiPos(2,11,5))
world.addObjectAtPos (KikiStone(), KikiPos(2,13,18))
world.addObjectAtPos (KikiStone(), KikiPos(7,11,18))
world.addObjectAtPos (KikiStone(), KikiPos(7,9,18))
world.addObjectAtPos (KikiStone(), KikiPos(3,11,18))
world.addObjectAtPos (KikiStone(), KikiPos(3,9,10))
world.addObjectAtPos (KikiStone(), KikiPos(3,11,4))
world.addObjectAtPos (KikiStone(), KikiPos(3,13,10))
world.addObjectAtPos (KikiStone(), KikiPos(3,8,8))
world.addObjectAtPos (KikiStone(), KikiPos(3,6,16))
world.addObjectAtPos (KikiStone(), KikiPos(3,4,5))
world.addObjectAtPos (KikiStone(), KikiPos(18,6,5))
world.addObjectAtPos (KikiStone(), KikiPos(15,8,5))
world.addObjectAtPos (KikiStone(), KikiPos(15,6,8))
world.addObjectAtPos (KikiStone(), KikiPos(10,6,6))
world.addObjectAtPos (KikiStone(), KikiPos(8,6,10))
world.addObjectAtPos (KikiStone(), KikiPos(8,4,7))
world.addObjectAtPos (KikiStone(), KikiPos(10,4,12))
world.addObjectAtPos (KikiStone(), KikiPos(5,4,14))
world.addObjectAtPos (KikiStone(), KikiPos(8,6,14))
world.addObjectAtPos (KikiStone(), KikiPos(7,4,14))
world.addObjectAtPos (KikiStone(), KikiPos(7,6,16))
world.addObjectAtPos (KikiStone(), KikiPos(8,8,16))
world.addObjectAtPos (KikiStone(), KikiPos(8,10,7))
world.addObjectAtPos (KikiStone(), KikiPos(8,13,9))
world.addObjectAtPos (KikiStone(), KikiPos(8,15,4))
world.addObjectAtPos (KikiStone(), KikiPos(8,13,10))
world.addObjectAtPos (KikiStone(), KikiPos(8,7,8))
world.addObjectAtPos (KikiStone(), KikiPos(8,13,6))
world.addObjectAtPos (KikiStone(), KikiPos(4,13,8))
world.addObjectAtPos (KikiStone(), KikiPos(4,15,15))
world.addObjectAtPos (KikiStone(), KikiPos(4,18,17))
world.addObjectAtPos (KikiStone(), KikiPos(6,18,2))
world.addObjectAtPos (KikiStone(), KikiPos(10,18,4))
world.addObjectAtPos (KikiStone(), KikiPos(4,18,2))
world.addObjectAtPos (KikiStone(), KikiPos(18,16,2))
world.addObjectAtPos (KikiStone(), KikiPos(18,18,4))
world.addObjectAtPos (KikiStone(), KikiPos(16,5,4))
world.addObjectAtPos (KikiStone(), KikiPos(16,3,4))
world.addObjectAtPos (KikiStone(), KikiPos(3,5,4))
world.addObjectAtPos (KikiStone(), KikiPos(3,7,2))
world.addObjectAtPos (KikiStone(), KikiPos(13,9,2))
world.addObjectAtPos (KikiStone(), KikiPos(8,9,4))
world.addObjectAtPos (KikiStone(), KikiPos(2,9,2))
world.addObjectAtPos (KikiStone(), KikiPos(2,11,2))
world.addObjectAtPos (KikiStone(), KikiPos(4,11,12))
world.addObjectAtPos (KikiStone(), KikiPos(17,9,12))
world.addObjectAtPos (KikiStone(), KikiPos(17,7,14))
world.addObjectAtPos (KikiStone(), KikiPos(15,7,8))
world.addObjectAtPos (KikiStone(), KikiPos(17,15,8))
world.addObjectAtPos (KikiStone(), KikiPos(17,13,15))
world.addObjectAtPos (KikiStone(), KikiPos(6,11,15))
world.addObjectAtPos (KikiStone(), KikiPos(6,13,10))
world.addObjectAtPos (KikiStone(), KikiPos(6,2,12))
world.addObjectAtPos (KikiStone(), KikiPos(10,4,12))
world.addObjectAtPos (KikiStone(), KikiPos(12,4,10))
world.addObjectAtPos (KikiStone(), KikiPos(14,4,11))
world.addObjectAtPos (KikiStone(), KikiPos(14,2,12))
world.addObjectAtPos (KikiStone(), KikiPos(3,4,12))
world.addObjectAtPos (KikiStone(), KikiPos(5,14,12))
world.addObjectAtPos (KikiStone(), KikiPos(7,7,12))
world.addObjectAtPos (KikiStone(), KikiPos(7,5,2))
world.addObjectAtPos (KikiStone(), KikiPos(3,3,2))
world.addObjectAtPos (KikiStone(), KikiPos(3,5,9))
world.addObjectAtPos (KikiStone(), KikiPos(5,5,7))
world.addObjectAtPos (KikiStone(), KikiPos(7,6,7))
world.addObjectAtPos (KikiStone(), KikiPos(10,4,7))
world.addObjectAtPos (KikiStone(), KikiPos(12,10,7))
world.addObjectAtPos (KikiStone(), KikiPos(3,12,7))
world.addObjectAtPos (KikiStone(), KikiPos(5,12,7))
world.addObjectAtPos (KikiStone(), KikiPos(13,12,5))
world.addObjectAtPos (KikiStone(), KikiPos(8,12,3))
world.addObjectAtPos (KikiStone(), KikiPos(8,10,2))
world.addObjectAtPos (KikiStone(), KikiPos(8,8,13))
world.addObjectAtPos (KikiStone(), KikiPos(8,10,15))
world.addObjectAtPos (KikiStone(), KikiPos(8,12,17))
world.addObjectAtPos (KikiStone(), KikiPos(10,3,17))
world.addObjectAtPos (KikiStone(), KikiPos(11,3,15))
world.addObjectAtPos (KikiStone(), KikiPos(13,3,13))
world.addObjectAtPos (KikiStone(), KikiPos(13,5,12))
world.addObjectAtPos (KikiStone(), KikiPos(14,7,12))
world.addObjectAtPos (KikiStone(), KikiPos(16,18,12))
world.addObjectAtPos (KikiStone(), KikiPos(14,18,6))
world.addObjectAtPos (KikiStone(), KikiPos(12,18,14))
world.addObjectAtPos (KikiStone(), KikiPos(16,18,16))
world.addObjectAtPos (KikiStone(), KikiPos(2,18,14))
world.addObjectAtPos (KikiStone(), KikiPos(10,18,16))
world.addObjectAtPos (KikiStone(), KikiPos(7,18,14))
world.addObjectAtPos (KikiStone(), KikiPos(5,18,5))
world.addObjectAtPos (KikiStone(), KikiPos(3,18,12))
world.addObjectAtPos (KikiStone(), KikiPos(5,16,12))
world.addObjectAtPos (KikiStone(), KikiPos(5,16,14))
world.addObjectAtPos (KikiStone(), KikiPos(5,14,2))
world.addObjectAtPos (KikiStone(), KikiPos(8,12,2))
world.addObjectAtPos (KikiStone(), KikiPos(10,12,12))
world.addObjectAtPos (KikiStone(), KikiPos(12,6,12))
world.addObjectAtPos (KikiStone(), KikiPos(14,6,12))
world.addObjectAtPos (KikiStone(), KikiPos(14,9,14))
world.addObjectAtPos (KikiStone(), KikiPos(14,3,12))
world.addObjectAtPos (KikiStone(), KikiPos(11,3,10))
world.addObjectAtPos (KikiStone(), KikiPos(9,3,12))
world.addObjectAtPos (KikiStone(), KikiPos(7,3,12))
world.addObjectAtPos (KikiStone(), KikiPos(7,5,3))
world.addObjectAtPos (KikiStone(), KikiPos(7,7,14))
world.addObjectAtPos (KikiStone(), KikiPos(7,15,12))
world.addObjectAtPos (KikiStone(), KikiPos(18,17,12))
world.addObjectAtPos (KikiStone(), KikiPos(17,17,10))
world.addObjectAtPos (KikiStone(), KikiPos(17,15,15))
world.addObjectAtPos (KikiStone(), KikiPos(10,13,15))
world.addObjectAtPos (KikiStone(), KikiPos(8,11,15))
world.addObjectAtPos (KikiStone(), KikiPos(8,7,17))
world.addObjectAtPos (KikiStone(), KikiPos(18,9,17))
world.addObjectAtPos (KikiStone(), KikiPos(16,7,17))
world.addObjectAtPos (KikiStone(), KikiPos(14,3,17))
world.addObjectAtPos (KikiStone(), KikiPos(16,6,17))
world.addObjectAtPos (KikiStone(), KikiPos(14,6,14))
world.addObjectAtPos (KikiStone(), KikiPos(15,8,14))
world.addObjectAtPos (KikiStone(), KikiPos(17,8,12))
world.addObjectAtPos (KikiStone(), KikiPos(14,8,14))
world.addObjectAtPos (KikiStone(), KikiPos(16,2,14))
world.addObjectAtPos (KikiStone(), KikiPos(14,6,14))
world.addObjectAtPos (KikiStone(), KikiPos(16,6,14))
world.addObjectAtPos (KikiStone(), KikiPos(18,6,12))
world.addObjectAtPos (KikiStone(), KikiPos(18,4,12))
world.addObjectAtPos (KikiStone(), KikiPos(3,6,12))
world.addObjectAtPos (KikiStone(), KikiPos(3,6,14))
world.addObjectAtPos (KikiStone(), KikiPos(6,6,12))
world.addObjectAtPos (KikiStone(), KikiPos(10,4,12))
world.addObjectAtPos (KikiStone(), KikiPos(3,2,12))
world.addObjectAtPos (KikiStone(), KikiPos(3,2,10))
world.addObjectAtPos (KikiStone(), KikiPos(2,2,8))
world.addObjectAtPos (KikiStone(), KikiPos(2,4,13))
world.addObjectAtPos (KikiStone(), KikiPos(15,4,15))
world.addObjectAtPos (KikiStone(), KikiPos(13,4,15))
world.addObjectAtPos (KikiStone(), KikiPos(13,2,7))
world.addObjectAtPos (KikiStone(), KikiPos(11,15,7))
world.addObjectAtPos (KikiStone(), KikiPos(9,11,7))
world.addObjectAtPos (KikiStone(), KikiPos(7,2,7))
world.addObjectAtPos (KikiStone(), KikiPos(9,2,14))
world.addObjectAtPos (KikiStone(), KikiPos(9,4,18))
world.addObjectAtPos (KikiStone(), KikiPos(9,2,15))
world.addObjectAtPos (KikiStone(), KikiPos(7,2,4))
world.addObjectAtPos (KikiStone(), KikiPos(5,4,4))
world.addObjectAtPos (KikiStone(), KikiPos(5,6,2))
world.addObjectAtPos (KikiStone(), KikiPos(12,4,2))
world.addObjectAtPos (KikiStone(), KikiPos(3,4,4))
world.addObjectAtPos (KikiStone(), KikiPos(3,12,6))
world.addObjectAtPos (KikiStone(), KikiPos(2,12,4))
world.addObjectAtPos (KikiStone(), KikiPos(15,14,4))
world.addObjectAtPos (KikiStone(), KikiPos(7,12,4))
world.addObjectAtPos (KikiStone(), KikiPos(9,12,2))
world.addObjectAtPos (KikiStone(), KikiPos(14,12,4))
world.addObjectAtPos (KikiStone(), KikiPos(12,3,4))
world.addObjectAtPos (KikiStone(), KikiPos(14,10,4))
world.addObjectAtPos (KikiStone(), KikiPos(16,10,13))
world.addObjectAtPos (KikiStone(), KikiPos(15,8,13))
world.addObjectAtPos (KikiStone(), KikiPos(15,6,8))
world.addObjectAtPos (KikiStone(), KikiPos(17,15,8))
world.addObjectAtPos (KikiStone(), KikiPos(6,15,10))
world.addObjectAtPos (KikiStone(), KikiPos(3,13,10))
world.addObjectAtPos (KikiStone(), KikiPos(15,15,10))
world.addObjectAtPos (KikiStone(), KikiPos (19,4,4))
""",                                 
}

# .................................................................................................................

